language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.2
install: bundle install
gemfile:
  - Gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
